# Generated with coinbase fiat currencies api and chatgpt so there might be mistakes


class Currency:
    def __init__(
        self,
        name: str,
        symbol: str,
        min_sendable: int,
        max_sendable: int,
        decimals: int,
    ) -> None:
        self.name = name
        self.symbol = symbol
        self.min_sendable = min_sendable
        self.max_sendable = max_sendable
        self.decimals = decimals


CURRENCIES: dict[str, Currency] = {
    "SAT": Currency(
        name="Satoshis",
        symbol="SAT",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "AED": Currency(
        name="United Arab Emirates Dirham",
        symbol="د.إ",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "AFN": Currency(
        name="Afghan Afghani",
        symbol="؋",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "ALL": Currency(
        name="Albanian Lek",
        symbol="L",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "AMD": Currency(
        name="Armenian Dram",
        symbol="֏",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "ANG": Currency(
        name="Netherlands Antillean Gulden",
        symbol="ƒ",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "AOA": Currency(
        name="Angolan Kwanza",
        symbol="Kz",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "ARS": Currency(
        name="Argentine Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "AUD": Currency(
        name="Australian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "AWG": Currency(
        name="Aruban Florin",
        symbol="ƒ",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "AZN": Currency(
        name="Azerbaijani Manat",
        symbol="₼",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BAM": Currency(
        name="Bosnia and Herzegovina Convertible Mark",
        symbol="KM",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BBD": Currency(
        name="Barbadian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BDT": Currency(
        name="Bangladeshi Taka",
        symbol="৳",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BGN": Currency(
        name="Bulgarian Lev",
        symbol="лв",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BHD": Currency(
        name="Bahraini Dinar",
        symbol=".د.ب",
        min_sendable=1,
        max_sendable=10000000,
        decimals=3,
    ),
    "BIF": Currency(
        name="Burundian Franc",
        symbol="FBu",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "BMD": Currency(
        name="Bermudian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BND": Currency(
        name="Brunei Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BOB": Currency(
        name="Bolivian Boliviano",
        symbol="Bs",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BRL": Currency(
        name="Brazilian Real",
        symbol="R$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BSD": Currency(
        name="Bahamian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BTN": Currency(
        name="Bhutanese Ngultrum",
        symbol="Nu.",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BWP": Currency(
        name="Botswana Pula",
        symbol="P",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BYN": Currency(
        name="Belarusian Ruble",
        symbol="Br",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "BYR": Currency(
        name="Belarusian Ruble",
        symbol="Br",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "BZD": Currency(
        name="Belize Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CAD": Currency(
        name="Canadian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CDF": Currency(
        name="Congolese Franc",
        symbol="FC",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CHF": Currency(
        name="Swiss Franc",
        symbol="CHF",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CLF": Currency(
        name="Unidad de Fomento",
        symbol="UF",
        min_sendable=1,
        max_sendable=10000000,
        decimals=4,
    ),
    "CLP": Currency(
        name="Chilean Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "CNY": Currency(
        name="Chinese Renminbi Yuan",
        symbol="¥",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "COP": Currency(
        name="Colombian Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CRC": Currency(
        name="Costa Rican Colón",
        symbol="₡",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CUC": Currency(
        name="Cuban Convertible Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CUP": Currency(
        name="Cuban Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CVE": Currency(
        name="Cape Verdean Escudo",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "CZK": Currency(
        name="Czech Koruna",
        symbol="Kč",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "DJF": Currency(
        name="Djiboutian Franc",
        symbol="Fdj",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "DKK": Currency(
        name="Danish Krone",
        symbol="kr",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "DOP": Currency(
        name="Dominican Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "DZD": Currency(
        name="Algerian Dinar",
        symbol="د.ج",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "EGP": Currency(
        name="Egyptian Pound",
        symbol="ج.م",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "ERN": Currency(
        name="Eritrean Nakfa",
        symbol="Nkf",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "ETB": Currency(
        name="Ethiopian Birr",
        symbol="Br",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "EUR": Currency(
        name="Euro",
        symbol="€",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "FJD": Currency(
        name="Fijian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "FKP": Currency(
        name="Falkland Islands Pound",
        symbol="£",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "GBP": Currency(
        name="British Pound Sterling",
        symbol="£",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "GEL": Currency(
        name="Georgian Lari",
        symbol="₾",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "GHS": Currency(
        name="Ghanaian Cedi",
        symbol="₵",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "GIP": Currency(
        name="Gibraltar Pound",
        symbol="£",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "GMD": Currency(
        name="Gambian Dalasi",
        symbol="D",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "GNF": Currency(
        name="Guinean Franc",
        symbol="FG",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "GTQ": Currency(
        name="Guatemalan Quetzal",
        symbol="Q",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "GYD": Currency(
        name="Guyanese Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "HKD": Currency(
        name="Hong Kong Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "HNL": Currency(
        name="Honduran Lempira",
        symbol="L",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "HRK": Currency(
        name="Croatian Kuna",
        symbol="kn",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "HTG": Currency(
        name="Haitian Gourde",
        symbol="G",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "HUF": Currency(
        name="Hungarian Forint",
        symbol="Ft",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "IDR": Currency(
        name="Indonesian Rupiah",
        symbol="Rp",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "ILS": Currency(
        name="Israeli New Shekel",
        symbol="₪",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "INR": Currency(
        name="Indian Rupee",
        symbol="₹",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "IQD": Currency(
        name="Iraqi Dinar",
        symbol="ع.د",
        min_sendable=1,
        max_sendable=10000000,
        decimals=3,
    ),
    "IRR": Currency(
        name="Iranian Rial",
        symbol="﷼",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "ISK": Currency(
        name="Icelandic Króna",
        symbol="kr",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "JMD": Currency(
        name="Jamaican Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "JOD": Currency(
        name="Jordanian Dinar",
        symbol="د.أ",
        min_sendable=1,
        max_sendable=10000000,
        decimals=3,
    ),
    "JPY": Currency(
        name="Japanese Yen",
        symbol="¥",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "KES": Currency(
        name="Kenyan Shilling",
        symbol="Ksh",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "KGS": Currency(
        name="Kyrgyzstani Som",
        symbol="с",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "KHR": Currency(
        name="Cambodian Riel",
        symbol="៛",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "KPW": Currency(
        name="North Korean Won",
        symbol="₩",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "KRW": Currency(
        name="South Korean Won",
        symbol="₩",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "KWD": Currency(
        name="Kuwaiti Dinar",
        symbol="د.ك",
        min_sendable=1,
        max_sendable=10000000,
        decimals=3,
    ),
    "KYD": Currency(
        name="Cayman Islands Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "KZT": Currency(
        name="Kazakhstani Tenge",
        symbol="₸",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "LAK": Currency(
        name="Lao Kip",
        symbol="₭",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "LBP": Currency(
        name="Lebanese Pound",
        symbol="ل.ل",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "LKR": Currency(
        name="Sri Lankan Rupee",
        symbol="Rs",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "LRD": Currency(
        name="Liberian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "LSL": Currency(
        name="Lesotho Loti",
        symbol="M",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "LYD": Currency(
        name="Libyan Dinar",
        symbol="ل.د",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MAD": Currency(
        name="Moroccan Dirham",
        symbol="د.م.",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MDL": Currency(
        name="Moldovan Leu",
        symbol="L",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MGA": Currency(
        name="Malagasy Ariary",
        symbol="Ar",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "MKD": Currency(
        name="Macedonian Denar",
        symbol="ден",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MMK": Currency(
        name="Myanmar Kyat",
        symbol="K",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "MOP": Currency(
        name="Macanese Pataca",
        symbol="MOP$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MRU": Currency(
        name="Mauritanian Ouguiya",
        symbol="UM",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "MUR": Currency(
        name="Mauritian Rupee",
        symbol="Rs",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MVR": Currency(
        name="Maldivian Rufiyaa",
        symbol="MVR",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MXN": Currency(
        name="Mexican Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MYR": Currency(
        name="Malaysian Ringgit",
        symbol="RM",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "MZN": Currency(
        name="Mozambican Metical",
        symbol="MT",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "NAD": Currency(
        name="Namibian Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "NGN": Currency(
        name="Nigerian Naira",
        symbol="₦",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "NIO": Currency(
        name="Nicaraguan Córdoba",
        symbol="C$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "NOK": Currency(
        name="Norwegian Krone",
        symbol="kr",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "NZD": Currency(
        name="New Zealand Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "OMR": Currency(
        name="Omani Rial",
        symbol="ر.ع.",
        min_sendable=1,
        max_sendable=10000000,
        decimals=3,
    ),
    "PAB": Currency(
        name="Panamanian Balboa",
        symbol="B/. ",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "PEN": Currency(
        name="Peruvian Sol",
        symbol="S/.",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "PGK": Currency(
        name="Papua New Guinean Kina",
        symbol="K",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "PHP": Currency(
        name="Philippine Peso",
        symbol="₱",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "PKR": Currency(
        name="Pakistani Rupee",
        symbol="Rs",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "PLN": Currency(
        name="Polish Zloty",
        symbol="zł",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "PYG": Currency(
        name="Paraguayan Guarani",
        symbol="₲",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "QAR": Currency(
        name="Qatari Rial",
        symbol="ر.ق",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "RON": Currency(
        name="Romanian Leu",
        symbol="lei",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "RSD": Currency(
        name="Serbian Dinar",
        symbol="дин.",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "RUB": Currency(
        name="Russian Ruble",
        symbol="₽",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "RWF": Currency(
        name="Rwandan Franc",
        symbol="FRw",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "SAR": Currency(
        name="Saudi Riyal",
        symbol="ر.س",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SBD": Currency(
        name="Solomon Islands Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SCR": Currency(
        name="Seychellois Rupee",
        symbol="₨",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SDG": Currency(
        name="Sudanese Pound",
        symbol="ج.س.",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SEK": Currency(
        name="Swedish Krona",
        symbol="kr",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SGD": Currency(
        name="Singapore Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SHP": Currency(
        name="Saint Helena Pound",
        symbol="£",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SLL": Currency(
        name="Sierra Leonean Leone",
        symbol="Le",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "SOS": Currency(
        name="Somali Shilling",
        symbol="S",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "SRD": Currency(
        name="Surinamese Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SYP": Currency(
        name="Syrian Pound",
        symbol="ل.س",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "SZL": Currency(
        name="Swazi Lilangeni",
        symbol="E",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "THB": Currency(
        name="Thai Baht",
        symbol="฿",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TJS": Currency(
        name="Tajikistani Somoni",
        symbol="SM",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TMT": Currency(
        name="Turkmenistani Manat",
        symbol="T",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TND": Currency(
        name="Tunisian Dinar",
        symbol="د.ت",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TOP": Currency(
        name="Tongan Paʻanga",
        symbol="T$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TRY": Currency(
        name="Turkish Lira",
        symbol="₺",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TTD": Currency(
        name="Trinidad and Tobago Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TWD": Currency(
        name="New Taiwan Dollar",
        symbol="NT$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "TZS": Currency(
        name="Tanzanian Shilling",
        symbol="TSh",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "UAH": Currency(
        name="Ukrainian Hryvnia",
        symbol="₴",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "UGX": Currency(
        name="Ugandan Shilling",
        symbol="USh",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "USD": Currency(
        name="United States Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "UYU": Currency(
        name="Uruguayan Peso",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "UZS": Currency(
        name="Uzbekistani Som",
        symbol="лв",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "VES": Currency(
        name="Venezuelan Bolívar",
        symbol="Bs.",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "VND": Currency(
        name="Vietnamese Dong",
        symbol="₫",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "VUV": Currency(
        name="Vanuatu Vatu",
        symbol="Vt",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "WST": Currency(
        name="Samoan Tala",
        symbol="T",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "XAF": Currency(
        name="Central African CFA Franc",
        symbol="FCFA",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "XCD": Currency(
        name="East Caribbean Dollar",
        symbol="$",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "XOF": Currency(
        name="West African CFA Franc",
        symbol="CFA",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "XPF": Currency(
        name="CFP Franc",
        symbol="₣",
        min_sendable=1,
        max_sendable=10000000,
        decimals=0,
    ),
    "ZAR": Currency(
        name="South African Rand",
        symbol="R",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
    "ZMW": Currency(
        name="Zambian Kwacha",
        symbol="ZK",
        min_sendable=1,
        max_sendable=10000000,
        decimals=2,
    ),
}
