"""adding new counterparty requrements and per wallet fields

Revision ID: 115fd8d013a7
Revises: dd262f9fd9b9
Create Date: 2025-11-15 10:15:42.162799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "115fd8d013a7"
down_revision: Union[str, None] = "dd262f9fd9b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first (required for PostgreSQL)
    bank_account_name_matching_status_enum = sa.Enum(
        "UNKNOWN",
        "MATCHED",
        "NOT_MATCHED",
        name="bankaccountnamematchingstatus",
    )
    wallet_user_type_enum = sa.Enum(
        "INDIVIDUAL",
        "BUSINESS",
        name="walletusertype",
    )

    # Create the enum types in the database
    bank_account_name_matching_status_enum.create(op.get_bind(), checkfirst=True)
    wallet_user_type_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("wallet", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "required_counterparty_fields",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "bank_account_name_matching_status",
                bank_account_name_matching_status_enum,
                server_default="UNKNOWN",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("phone_number", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("nationality", sa.String(length=2), nullable=True)
        )
        batch_op.add_column(sa.Column("address", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("tax_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("financial_institution_lei", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("account_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("account_identifier", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "user_type",
                wallet_user_type_enum,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("fi_legal_entity_name", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "ultimate_institution_country", sa.String(length=2), nullable=True
            )
        )

    op.execute(
        "UPDATE wallet SET required_counterparty_fields = '[]' WHERE required_counterparty_fields IS NULL"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallet", schema=None) as batch_op:
        batch_op.drop_column("ultimate_institution_country")
        batch_op.drop_column("fi_legal_entity_name")
        batch_op.drop_column("user_type")
        batch_op.drop_column("account_identifier")
        batch_op.drop_column("account_name")
        batch_op.drop_column("financial_institution_lei")
        batch_op.drop_column("tax_id")
        batch_op.drop_column("address")
        batch_op.drop_column("nationality")
        batch_op.drop_column("phone_number")
        batch_op.drop_column("bank_account_name_matching_status")
        batch_op.drop_column("required_counterparty_fields")

    # Drop enum types after dropping the columns
    sa.Enum(name="walletusertype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="bankaccountnamematchingstatus").drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
