"""add country_of_residence and birthday to user table

Revision ID: 65731fa8f965
Revises: d0875f916591
Create Date: 2025-08-18 16:22:34.686866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65731fa8f965"
down_revision: Union[str, None] = "d0875f916591"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("country_of_residence", sa.String(length=2), nullable=True)
    )
    op.add_column("user", sa.Column("birthday", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "birthday")
    op.drop_column("user", "country_of_residence")
    # ### end Alembic commands ###
