"""add delete cascade to wallet uma and currency

Revision ID: 981b7e525643
Revises: f3cc7214cccf
Create Date: 2025-01-07 17:35:40.158447

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "981b7e525643"
down_revision: Union[str, None] = "f3cc7214cccf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
