"""add last_used column to push subscription table

Revision ID: bf91aca96fc9
Revises: 653c26cf3fa2
Create Date: 2024-12-11 13:53:09.497356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf91aca96fc9"
down_revision: Union[str, None] = "653c26cf3fa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("push_subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_used",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("push_subscription", schema=None) as batch_op:
        batch_op.drop_column("last_used")

    # ### end Alembic commands ###
