"""backfilling all accounts to be user_type INDIVIDUAL

Revision ID: e9410c3bf621
Revises: 115fd8d013a7
Create Date: 2025-12-04 14:24:04.522611

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9410c3bf621"
down_revision: Union[str, None] = "115fd8d013a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE wallet SET user_type = 'INDIVIDUAL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
